FROM alpine:latest

#Original Maintainer;
Henrik Lissner <henrik@lissner.net>

#Forked by Victxrlarixs

RUN apk add --update nginx && rm -rf /var/cache/apk/*
COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN ln -svf /dev/stdout /var/log/nginx/access.log
RUN ln -svf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
